services:
  postgresql:
    image: postgres:16
    env_file: "./.env"
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend
  liquibase-scrapper-migrations:
    image: liquibase/liquibase:4.25
    env_file: "./.env"
    depends_on:
      - postgresql
    command:
      - --changelog-file=scrapper-db.yaml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/${SCRAPPER_DB_DATABASE}
      - --username=${DB_USERNAME}
      - --password=${DB_PASSWORD}
      - update
    volumes:
      - ./scrapper/src/main/resources/db/changelog:/liquibase/changelog
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }
