app:
  scheduler:
    enabled: false
    interval: PT10S
    force-check-delay: 10s

github-client:
  base-url: ${GITHUB_BASE_URL:"https://api.github.com"}

stack-overflow-client:
  base-url: ${STACK_OVERFLOW_BASE_URL:"https://api.stackexchange.com/2.3"}


spring:
  application:
    name: scrapper

server:
  port: ${SCRAPPER_SERVER_PORT:8080}

logging:
  config: classpath:log4j2-plain.xml
