app:
  telegram-token: ${BOT_TELEGRAM_TOKEN}

scrapper-client:
  base-url: ${BOT_CLIENT_BASE_URL:"https://localhost:8090"}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: ${BOT_SERVER_PORT:8090}

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
